export const result = {
  success: true,
  courses: [
    {
      id: 23804,
      name: '2023 Core JAVA Bootcamp from Zero to Hero',
      image: 'https://img-c.udemycdn.com/course/750x422/4987312_8657_4.jpg',
      price: 19.99,
      sale_price: 0,
      lectures: 15,
      views: 26881,
      rating: 5,
      language: 'English',
      category: 'Development',
      subcategory: 'Programming Languages',
      slug: '2023-core-java-bootcamp-from-zero-to-hero-23804',
      store: 'Udemy',
      sale_start: '2025-08-23 05:07:41',
    },
    {
      id: 74045,
      name: 'Advanced AI Course 2025: ChatGPT, Midjourney, Gemini Firefly',
      image: 'https://img-c.udemycdn.com/course/750x422/6721188_64fb.jpg',
      price: 44.99,
      sale_price: 0,
      lectures: 31,
      views: 335,
      rating: 0,
      language: 'English',
      category: 'Business',
      subcategory: 'Management',
      slug: 'advanced-ai-course-2025-chatgpt-midjourney-gemini--328',
      store: 'Udemy',
      sale_start: '2025-08-23 04:57:12',
    },
    {
      id: 74046,
      name: 'Digital Marketing Bootcamp 2025: SEO, PPC, SMM, GTM, Email!',
      image: 'https://img-c.udemycdn.com/course/750x422/6707443_ef4a.jpg',
      price: 44.99,
      sale_price: 0,
      lectures: 48,
      views: 358,
      rating: 5,
      language: 'English',
      category: 'Marketing',
      subcategory: 'Digital Marketing',
      slug: 'digital-marketing-bootcamp-2025-seo-ppc-smm-gtm-em-329',
      store: 'Udemy',
      sale_start: '2025-08-23 04:47:02',
    },
    {
      id: 30423,
      name: 'Learn C++ Programming - Beginner to Advanced',
      image: 'https://img-c.udemycdn.com/course/750x422/4871278_dc28_4.jpg',
      price: 19.99,
      sale_price: 0,
      lectures: 10,
      views: 9549,
      rating: 4.35,
      language: 'English',
      category: 'IT & Software',
      subcategory: 'IT Certifications',
      slug: 'learn-c-programming-beginner-to-advanced-30423',
      store: 'Udemy',
      sale_start: '2025-08-23 04:36:31',
    },
    {
      id: 71232,
      name: 'Pharmacovigilance Course',
      image: 'https://img-c.udemycdn.com/course/750x422/5521094_9c66.jpg',
      price: 19.99,
      sale_price: 0,
      lectures: 10,
      views: 1721,
      rating: 3.95,
      language: 'English',
      category: 'Teaching & Academics',
      subcategory: 'Other Teaching & Academics',
      slug: 'pharmacovigilance-course-862',
      store: 'Udemy',
      sale_start: '2025-08-23 04:32:33',
    },
    {
      id: 68814,
      name: 'CRISPR Cas9 Technology',
      image: 'https://img-c.udemycdn.com/course/750x422/4904848_3897_2.jpg',
      price: 19.99,
      sale_price: 0,
      lectures: 38,
      views: 2136,
      rating: 4.2,
      language: 'English',
      category: 'Teaching & Academics',
      subcategory: 'Science',
      slug: 'crispr-cas9-technology-577',
      store: 'Udemy',
      sale_start: '2025-08-23 04:30:30',
    },
  ],
  totalItems: 80,
  currentPage: 1,
  totalPages: 14,
};

export const course = {
  id: 25768,
  name: 'Data Structures and OOP with C++ | CS105, C104 Masterclass',
  description:
    '<p>Welcome to our CS104, C105 Masterclass! In this class, we will dive into the world of Data Structures and Object-Oriented Programming (OOP) using the popular programming language, C++.</p><p>Data structures are an essential part of computer science, as they provide an organized way of storing and manipulating data. By using data structures, we can access and modify data more efficiently, which is essential for developing efficient and effective software.</p><p>In our class, we will cover various data structures, including arrays, linked lists, stacks, queues, and trees. We will explore how to implement these structures in C++ and how to perform basic operations like insertion, deletion, and searching. Additionally, we will discuss the advantages and disadvantages of each data structure and when to use them in different situations.</p><p>Linked lists, for example, are a popular data structure used to store and manage data in a sequence. Linked lists are efficient because they can be dynamically allocated and are flexible in size. However, they can be more complicated to implement and use than other data structures like arrays.</p><p>Stacks and queues are also important data structures that are commonly used in software development. Stacks use the "last in, first out" (LIFO) principle, while queues use the "first in, first out" (FIFO) principle. These data structures are useful for managing data in a specific order, and we will learn how to implement and use them in our class.</p><p>Trees are another popular data structure that we will cover in our class. Trees are useful for organizing data in a hierarchical structure and are often used in computer science applications like file systems, databases, and search engines.</p><p>In addition to data structures, we will also cover the basics of OOP in C++. Object-oriented programming focuses on encapsulation, inheritance, and polymorphism. With OOP, we can create reusable code, improve code organization and structure, and make code maintenance more manageable.</p><p>In our class, we will cover the basics of OOP in C++, including classes, objects, constructors, and destructors. We will also discuss inheritance, polymorphism, and encapsulation, and how they can be used to improve the functionality of our programs.</p><p>C++ is a powerful programming language known for its speed and efficiency. It is widely used in developing operating systems, embedded systems, and gaming applications. With C++, we can take advantage of its powerful features to create complex programs with high performance.</p><p>In our class, we will explore the C++ syntax and how it can be used to implement data structures and OOP concepts. We will also learn how to optimize our code for performance and efficiency.</p><p>To wrap it up, our CS104, C105 Masterclass will provide you with a solid foundation in Data Structures and Object-Oriented Programming with C++. You will learn how to implement data structures, use OOP concepts to improve your code, and take advantage of the powerful features of C++.</p>',
  content:
    '<p>Welcome to our CS104, C105 Masterclass! In this class, we will dive into the world of Data Structures and Object-Oriented Programming (OOP) using the popular programming language, C++.</p><p>Data structures are an essential part of computer science, as they provide an organized way of storing and manipulating data. By using data structures, we can access and modify data more efficiently, which is essential for developing efficient and effective software.</p><p>In our class, we will cover various data structures, including arrays, linked lists, stacks, queues, and trees. We will explore how to implement these structures in C++ and how to perform basic operations like insertion, deletion, and searching. Additionally, we will discuss the advantages and disadvantages of each data structure and when to use them in different situations.</p><p>Linked lists, for example, are a popular data structure used to store and manage data in a sequence. Linked lists are efficient because they can be dynamically allocated and are flexible in size. However, they can be more complicated to implement and use than other data structures like arrays.</p><p>Stacks and queues are also important data structures that are commonly used in software development. Stacks use the "last in, first out" (LIFO) principle, while queues use the "first in, first out" (FIFO) principle. These data structures are useful for managing data in a specific order, and we will learn how to implement and use them in our class.</p><p>Trees are another popular data structure that we will cover in our class. Trees are useful for organizing data in a hierarchical structure and are often used in computer science applications like file systems, databases, and search engines.</p><p>In addition to data structures, we will also cover the basics of OOP in C++. Object-oriented programming focuses on encapsulation, inheritance, and polymorphism. With OOP, we can create reusable code, improve code organization and structure, and make code maintenance more manageable.</p><p>In our class, we will cover the basics of OOP in C++, including classes, objects, constructors, and destructors. We will also discuss inheritance, polymorphism, and encapsulation, and how they can be used to improve the functionality of our programs.</p><p>C++ is a powerful programming language known for its speed and efficiency. It is widely used in developing operating systems, embedded systems, and gaming applications. With C++, we can take advantage of its powerful features to create complex programs with high performance.</p><p>In our class, we will explore the C++ syntax and how it can be used to implement data structures and OOP concepts. We will also learn how to optimize our code for performance and efficiency.</p><p>To wrap it up, our CS104, C105 Masterclass will provide you with a solid foundation in Data Structures and Object-Oriented Programming with C++. You will learn how to implement data structures, use OOP concepts to improve your code, and take advantage of the powerful features of C++.</p>',
  price: 219.99,
  sale_price: 0,
  sale_start: '2025-08-23 08:46:39',
  lectures: 8.5,
  views: 17959,
  rating: 0,
  image: 'https://img-c.udemycdn.com/course/750x422/5160672_2d22.jpg',
  url: 'https://www.udemy.com/course/data-structures-cpp/?couponCode=DATA-OP-OCSALY.COM',
  store: 'Udemy',
  type: 'external',
  slug: 'data-structures-and-oop-with-c-cs105-c104-masterclass-25768',
  category: 'Development',
  tags: '',
  subcategory: 'Software Engineering',
  language: 'English',
  courseid: 5160672,
};
